name: Beta release

on:
  push:
    branches:
      - main
    paths:
      - 'beta/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Log into registry
        run: echo "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}" | docker login -u stevapple --password-stdin
      - name: Build image
        run: docker build -t stevapple/swift-scf:beta beta
      - name: Release
        run: docker push stevapple/swift-scf:beta
