name: Nightly Autobuild

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Autobuild
        run: curl -XPOST ${{ secrets.DOCKERHUB_TRIGGER_ENDPOINT }}
