name: nightly

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Log into registry
        run: echo "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}" | docker login -u stevapple --password-stdin
      - name: Build and release nightly
        run: |
          cd nightly
          docker build -t stevapple/scf-swift:nightly .
          docker push stevapple/scf-swift:nightly