name: nightly

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Log into registry
        run: echo "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}" | docker login -u stevapple --password-stdin
      - name: Build nightly
        run: docker build -t stevapple/swift-scf:nightly nightly
      - name: Release
        run: docker push stevapple/swift-scf:nightly