name: Release 5.x

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (5.x)'
        required: true
      minor:
        description: 'The corresponding minor release'
        required: false

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Log into registry
        run: echo "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}" | docker login -u stevapple --password-stdin
      - name: Generate Dockerfile
        run: sed "s/#SWIFT_VERSION#/${{ github.event.inputs.version }}/g" 5.x/Dockerfile > Dockerfile
      - name: Build image
        run: docker build -t stevapple/swift-scf:${{ github.event.inputs.version }} .
      - name: Release
        run: docker push stevapple/swift-scf:${{ github.event.inputs.version }}
      - name: Update minor version
        if: ${{ startsWith(github.event.inputs.version, github.event.inputs.minor) }}
        run: |
          docker build -t stevapple/swift-scf:${{ github.event.inputs.minor }} .
          docker push stevapple/swift-scf:${{ github.event.inputs.minor }}
